### ISSUE TITLE
Include socials on wesbite

### ISSUE THREAD

**Issue by Etheriad** [CoryKlish/tropical-cardboard#20]
Add twitter handle @tropicalbb. add discord (not sure how to link to discord, buts its the tropical cardboard server we started a while back)

**Comment by CoryKlish** [comment]
@Etheriad Where do you want these placed? Red, Yellow, or Pink

![image](https://user-images.githubusercontent.com/32180969/202860090-f8964569-b871-416a-b608-2bcd7c124dbf.png)

**Comment by Etheriad** [comment]
Yellow
