### ISSUE TITLE
Need Metadata for SodaPhones

### ISSUE THREAD

**Issue by CoryKlish** [CoryKlish/tropical-cardboard#5]
### Description
In order for IPFS/OpenSea to link our images with contract, we need to populate metadata fields.

### Implementation Details
We should have one metadata file for each of our SodaPhones (12 total). Metadata must be a json file and contain at least the below fields:
```json
{
    "description": "Chill Soda Phone",
    "external_url": "https://www.tropicalcardboard.com",
    "image": "https://ipfs.io/ipfs/QmdkiEZrYPMEHNMoc4xMEq3WnMpE1ZUk9JTcJaBnU7QEes",
    "name": "Chill"
}
``` 
**Note**: The `image` field points to the IPFS hash we have on Pinata. The IPFS folder the SodaPhones are stored on can be found [here](https://ipfs.io/ipfs/QmZVhYjLoB3LVUbcURhsVP7ShNDzBsCXCBCKFoMbjNQXDY). We need to link the `image` field to the `.png` file for each of the SodaPhones. For the above example with "Chill", the image hash corresponds with what is defined in below image. The same pattern will apply for the rest.

![image](https://user-images.githubusercontent.com/32180969/187040414-2f2ad1f6-140d-40d7-a3ab-d62dda1feec6.png)

Also know that you are free to put whatever you like for the `description` (blue) and `name` (red) fields. These will display here:

![image](https://user-images.githubusercontent.com/32180969/187040722-333801ba-f9fc-47ec-8724-d29ee847543d.png)

Optionally, `attributes` can be added so that OpenSea can group/filter based on them. Consult the [OpenSea Metadata Standards](https://docs.opensea.io/docs/metadata-standards#metadata-structure) for descriptions of the fields and the form that they should take.

Files should be uploaded in a folder. The file names could be of the form `chill.json`, `chip.json`, etc. However, I do think the implementation _may_ be simpler if we name them with indexes. i.e. `0.json`, `1.json`, etc.

**Comment by Etheriad** [comment]
[SodaPhonesMetaData.txt](https://github.com/CoryKlish/tropical-cardboard/files/9438417/SodaPhonesMetaData.txt)

**Comment by CoryKlish** [comment]
> [SodaPhonesMetaData.txt](https://github.com/CoryKlish/tropical-cardboard/files/9438417/SodaPhonesMetaData.txt)

@Etheriad 
The format of the json looks good with the exception of those custom attributes listed. Each of these need to be in a separate `.json` file and put into a folder. The [OpenSea Metadata Standards](https://docs.opensea.io/docs/metadata-standards#metadata-structure) will help guide you for the format if you'd like to add the attributes.
