### ISSUE TITLE
Website welcome page

### ISSUE THREAD

**Issue by Etheriad** [CoryKlish/tropical-cardboard#6]
Welcome page that gives a greeting and walks through the steps of the project.

Welcome to the MetaVerse. Grab a soda.
![image](https://user-images.githubusercontent.com/111825703/188281495-dbd29bca-df9d-4afc-8dd2-a5da959d24b3.png)

**Comment by CoryKlish** [comment]
@Etheriad Resolved in #9 . Refer to the "View Deployment" button for validation



![image](https://user-images.githubusercontent.com/32180969/188752781-6291962a-27ec-427b-84aa-16003451cf73.png)
