### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by Etheriad** [CoryKlish/tropical-cardboard#8]
Create a menu for navigation on the website. 

About
Coin Exchange
Soda Machine
Meet the Team
References

**Comment by CoryKlish** [comment]
@Etheriad Resolved in #9 . Refer to the "View Deployment" button for validation. Let me know what you want each page to look like.



![image](https://user-images.githubusercontent.com/32180969/188752781-6291962a-27ec-427b-84aa-16003451cf73.png)
